In [52]:
import pandas as pd

df = pd.read_csv("Book_Details.csv")
df

,Unnamed: 0,book_id,cover_image_uri,book_title,book_details,format,publication_info,authorlink,author,num_pages,genres,num_ratings,num_reviews,average_rating,rating_distribution
0,0,1,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Half-Blood Prince,"It is the middle of the summer, but there is a...","['652 pages, Paperback']","['First published July 16, 2005']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['652'],"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",3292516,58398,4.58,"{'5': '2,244,154', '4': '775,028', '3': '219,8..."
1,1,2,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Order of the Phoenix,Harry Potter is about to start his fifth year ...,"['912 pages, Paperback']","['First published June 21, 2003']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['912'],"['Young Adult', 'Fiction', 'Magic', 'Childrens...",3401709,64300,4.50,"{'5': '2,178,760', '4': '856,178', '3': '293,2..."
2,2,3,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Sorcerer's Stone,Harry Potter has no idea how famous he is. Tha...,"['309 pages, Hardcover']","['First published June 26, 1997']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['309'],"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",10116247,163493,4.47,"{'5': '6,544,542', '4': '2,348,390', '3': '856..."
3,3,5,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Prisoner of Azkaban,"Harry Potter, along with his best friends, Ron...","['435 pages, Mass Market Paperback']","['First published July 8, 1999']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['435'],"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",4215031,84959,4.58,"{'5': '2,892,322', '4': '970,190', '3': '287,7..."
4,4,6,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Goblet of Fire,It is the summer holidays and soon Harry Potte...,"['734 pages, Paperback']","['First published July 8, 2000']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['734'],"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",3718209,69961,4.57,"{'5': '2,500,070', '4': '899,496', '3': '259,7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16220,16220,208877606,https://images-na.ssl-images-amazon.com/images...,Finistère,The 1920s. When wealthy American adolescent Ma...,"['316 pages, Paperback']","['First published January 1, 1951']",https://www.goodreads.com/author/show/151154.F...,Fritz Peters,['316'],"['Fiction', 'LGBT', 'Queer', 'Classics', 'Gay'...",129,22,3.77,"{'5': '36', '4': '41', '3': '41', '2': '8', '1..."
16221,16221,208877648,https://images-na.ssl-images-amazon.com/images...,The Descent,"Set in the 1950s, The Descent asks the questio...","['268 pages, Paperback']","['First published January 1, 1952']",https://www.goodreads.com/author/show/151154.F...,Fritz Peters,['268'],['Fiction'],4,0,4.75,"{'5': '3', '4': '1', '3': '0', '2': '0', '1': ..."
16222,16222,209251042,https://images-na.ssl-images-amazon.com/images...,FDR Unmasked: 73 Years of Medical Cover-ups Th...,THE HIDDEN ILLNESSES THAT SHAPED FDR’S LIFE AN...,"['316 pages, Paperback']","['Published February 27, 2024']",https://www.goodreads.com/author/show/2991326....,Steven Lomazow,['316'],"['Drama', 'Novels', 'Contemporary']",986,11,4.32,"{'5': '469', '4': '431', '3': '38', '2': '33',..."
16223,16223,209441121,https://images-na.ssl-images-amazon.com/images...,Code Yellow in Gretna Green,"In Gateway terminology, a ""Code Yellow"" signif...","['776 pages, Kindle Edition']","['Published March 28, 2024']",https://www.goodreads.com/author/show/22515164...,Linzi Day,['776'],"['Science Fiction Fantasy', 'Fantasy', 'Fictio...",1109,106,4.61,"{'5': '764', '4': '266', '3': '74', '2': '4', ..."
16224,16224,209607645,https://images-na.ssl-images-amazon.com/images...,Shadow's Siege,Shadow Island is under siege.Just a few short ...,"['254 pages, Kindle Edition']","['Published April 25, 2024']",https://www.goodreads.com/author/show/19007338...,Mary Stone,['254'],"['Drama', 'Novels', 'Crime', 'Thriller', 'Susp...",1271,37,4.64,"{'5': '914', '4': '277', '3': '70', '2': '5', ..."

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16225 entries, 0 to 16224
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           16225 non-null  int64
 1   book_id              16225 non-null  int64
 2   cover_image_uri      16225 non-null  object
 3   book_title           16225 non-null  object
 4   book_details         16177 non-null  object
 5   format               16225 non-null  object
 6   publication_info     16225 non-null  object
 7   authorlink           16225 non-null  object
 8   author               16225 non-null  object
 9   num_pages            16225 non-null  object
 10  genres               16225 non-null  object
 11  num_ratings          16225 non-null  int64
 12  num_reviews          16225 non-null  int64
 13  average_rating       16225 non-null  float64
 14  rating_distribution  16225 non-null  object
dtypes: float64(1), int64(4), object(10)
memory usage: 1.9+ MB

In [54]:
df.isna().sum()

Unnamed: 0              0
book_id                 0
cover_image_uri         0
book_title              0
book_details           48
format                  0
publication_info        0
authorlink              0
author                  0
num_pages               0
genres                  0
num_ratings             0
num_reviews             0
average_rating          0
rating_distribution     0
dtype: int64

In [55]:
df.dropna(inplace=True)
df.isna().sum()

Unnamed: 0             0
book_id                0
cover_image_uri        0
book_title             0
book_details           0
format                 0
publication_info       0
authorlink             0
author                 0
num_pages              0
genres                 0
num_ratings            0
num_reviews            0
average_rating         0
rating_distribution    0
dtype: int64

In [56]:
df.duplicated().sum()

np.int64(0)

In [57]:
df.columns

Index(['Unnamed: 0', 'book_id', 'cover_image_uri', 'book_title',
       'book_details', 'format', 'publication_info', 'authorlink', 'author',
       'num_pages', 'genres', 'num_ratings', 'num_reviews', 'average_rating',
       'rating_distribution'],
      dtype='object')

In [58]:
df.drop(columns="Unnamed: 0",inplace=True)
df

,book_id,cover_image_uri,book_title,book_details,format,publication_info,authorlink,author,num_pages,genres,num_ratings,num_reviews,average_rating,rating_distribution
0,1,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Half-Blood Prince,"It is the middle of the summer, but there is a...","['652 pages, Paperback']","['First published July 16, 2005']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['652'],"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",3292516,58398,4.58,"{'5': '2,244,154', '4': '775,028', '3': '219,8..."
1,2,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Order of the Phoenix,Harry Potter is about to start his fifth year ...,"['912 pages, Paperback']","['First published June 21, 2003']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['912'],"['Young Adult', 'Fiction', 'Magic', 'Childrens...",3401709,64300,4.50,"{'5': '2,178,760', '4': '856,178', '3': '293,2..."
2,3,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Sorcerer's Stone,Harry Potter has no idea how famous he is. Tha...,"['309 pages, Hardcover']","['First published June 26, 1997']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['309'],"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",10116247,163493,4.47,"{'5': '6,544,542', '4': '2,348,390', '3': '856..."
3,5,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Prisoner of Azkaban,"Harry Potter, along with his best friends, Ron...","['435 pages, Mass Market Paperback']","['First published July 8, 1999']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['435'],"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",4215031,84959,4.58,"{'5': '2,892,322', '4': '970,190', '3': '287,7..."
4,6,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Goblet of Fire,It is the summer holidays and soon Harry Potte...,"['734 pages, Paperback']","['First published July 8, 2000']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['734'],"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",3718209,69961,4.57,"{'5': '2,500,070', '4': '899,496', '3': '259,7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16220,208877606,https://images-na.ssl-images-amazon.com/images...,Finistère,The 1920s. When wealthy American adolescent Ma...,"['316 pages, Paperback']","['First published January 1, 1951']",https://www.goodreads.com/author/show/151154.F...,Fritz Peters,['316'],"['Fiction', 'LGBT', 'Queer', 'Classics', 'Gay'...",129,22,3.77,"{'5': '36', '4': '41', '3': '41', '2': '8', '1..."
16221,208877648,https://images-na.ssl-images-amazon.com/images...,The Descent,"Set in the 1950s, The Descent asks the questio...","['268 pages, Paperback']","['First published January 1, 1952']",https://www.goodreads.com/author/show/151154.F...,Fritz Peters,['268'],['Fiction'],4,0,4.75,"{'5': '3', '4': '1', '3': '0', '2': '0', '1': ..."
16222,209251042,https://images-na.ssl-images-amazon.com/images...,FDR Unmasked: 73 Years of Medical Cover-ups Th...,THE HIDDEN ILLNESSES THAT SHAPED FDR’S LIFE AN...,"['316 pages, Paperback']","['Published February 27, 2024']",https://www.goodreads.com/author/show/2991326....,Steven Lomazow,['316'],"['Drama', 'Novels', 'Contemporary']",986,11,4.32,"{'5': '469', '4': '431', '3': '38', '2': '33',..."
16223,209441121,https://images-na.ssl-images-amazon.com/images...,Code Yellow in Gretna Green,"In Gateway terminology, a ""Code Yellow"" signif...","['776 pages, Kindle Edition']","['Published March 28, 2024']",https://www.goodreads.com/author/show/22515164...,Linzi Day,['776'],"['Science Fiction Fantasy', 'Fantasy', 'Fictio...",1109,106,4.61,"{'5': '764', '4': '266', '3': '74', '2': '4', ..."
16224,209607645,https://images-na.ssl-images-amazon.com/images...,Shadow's Siege,Shadow Island is under siege.Just a few short ...,"['254 pages, Kindle Edition']","['Published April 25, 2024']",https://www.goodreads.com/author/show/19007338...,Mary Stone,['254'],"['Drama', 'Novels', 'Crime', 'Thriller', 'Susp...",1271,37,4.64,"{'5': '914', '4': '277', '3': '70', '2': '5', ..."

In [59]:
df["book_title"][0]

'Harry Potter and the Half-Blood Prince'

In [60]:
df["book_title"] = df["book_title"].apply(lambda x: x.split())
df["book_title"][0]

['Harry', 'Potter', 'and', 'the', 'Half-Blood', 'Prince']

In [61]:
df.columns

Index(['book_id', 'cover_image_uri', 'book_title', 'book_details', 'format',
       'publication_info', 'authorlink', 'author', 'num_pages', 'genres',
       'num_ratings', 'num_reviews', 'average_rating', 'rating_distribution'],
      dtype='object')

In [62]:
df["book_details"][0]

"It is the middle of the summer, but there is an unseasonal mist pressing against the windowpanes. Harry Potter is waiting nervously in his bedroom at the Dursleys' house in Privet Drive for a visit from Professor Dumbledore himself. One of the last times he saw the Headmaster, he was in a fierce one-to-one duel with Lord Voldemort, and Harry can't quite believe that Professor Dumbledore will actually appear at the Dursleys' of all places. Why is the Professor coming to visit him now? What is it that cannot wait until Harry returns to Hogwarts in a few weeks' time? Harry's sixth year at Hogwarts has already got off to an unusual start, as the worlds of Muggle and magic start to intertwine..."

In [63]:
df["book_details"] = df["book_details"].apply(lambda x: x.split())
df["book_details"][0]

['It',
 'is',
 'the',
 'middle',
 'of',
 'the',
 'summer,',
 'but',
 'there',
 'is',
 'an',
 'unseasonal',
 'mist',
 'pressing',
 'against',
 'the',
 'windowpanes.',
 'Harry',
 'Potter',
 'is',
 'waiting',
 'nervously',
 'in',
 'his',
 'bedroom',
 'at',
 'the',
 "Dursleys'",
 'house',
 'in',
 'Privet',
 'Drive',
 'for',
 'a',
 'visit',
 'from',
 'Professor',
 'Dumbledore',
 'himself.',
 'One',
 'of',
 'the',
 'last',
 'times',
 'he',
 'saw',
 'the',
 'Headmaster,',
 'he',
 'was',
 'in',
 'a',
 'fierce',
 'one-to-one',
 'duel',
 'with',
 'Lord',
 'Voldemort,',
 'and',
 'Harry',
 "can't",
 'quite',
 'believe',
 'that',
 'Professor',
 'Dumbledore',
 'will',
 'actually',
 'appear',
 'at',
 'the',
 "Dursleys'",
 'of',
 'all',
 'places.',
 'Why',
 'is',
 'the',
 'Professor',
 'coming',
 'to',
 'visit',
 'him',
 'now?',
 'What',
 'is',
 'it',
 'that',
 'cannot',
 'wait',
 'until',
 'Harry',
 'returns',
 'to',
 'Hogwarts',
 'in',
 'a',
 'few',
 "weeks'",
 'time?',
 "Harry's",
 'sixth',
 'year',
 'at',
 'Hogwarts',
 'has',
 'already',
 'got',
 'off',
 'to',
 'an',
 'unusual',
 'start,',
 'as',
 'the',
 'worlds',
 'of',
 'Muggle',
 'and',
 'magic',
 'start',
 'to',
 'intertwine...']

In [64]:
df["format"][0]

"['652 pages, Paperback']"

In [65]:
import ast

In [66]:
df["format"] = df["format"].apply(ast.literal_eval)
df["format"][3]

['435 pages, Mass Market Paperback']

In [ ]:

def change_format(x):
    lis= []
    for i in x:
        lis.append(i.split(","))
    return lis

In [68]:
df["format"] = df["format"].apply(change_format)
df["format"][0]

[['652 pages', ' Paperback']]

In [69]:
def change(x):
    lis = []
    for i in x:
        for j in i:
            lis.append(j)
    return lis
df["format"] = df["format"].apply(change)

In [70]:
df["format"][0]

['652 pages', ' Paperback']

In [71]:
df

,book_id,cover_image_uri,book_title,book_details,format,publication_info,authorlink,author,num_pages,genres,num_ratings,num_reviews,average_rating,rating_distribution
0,1,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Half-Blood, Prince]","[It, is, the, middle, of, the, summer,, but, t...","[652 pages, Paperback]","['First published July 16, 2005']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['652'],"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",3292516,58398,4.58,"{'5': '2,244,154', '4': '775,028', '3': '219,8..."
1,2,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Order, of, the, Phoe...","[Harry, Potter, is, about, to, start, his, fif...","[912 pages, Paperback]","['First published June 21, 2003']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['912'],"['Young Adult', 'Fiction', 'Magic', 'Childrens...",3401709,64300,4.50,"{'5': '2,178,760', '4': '856,178', '3': '293,2..."
2,3,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Sorcerer's, Stone]","[Harry, Potter, has, no, idea, how, famous, he...","[309 pages, Hardcover]","['First published June 26, 1997']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['309'],"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",10116247,163493,4.47,"{'5': '6,544,542', '4': '2,348,390', '3': '856..."
3,5,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Prisoner, of, Azkaban]","[Harry, Potter,, along, with, his, best, frien...","[435 pages, Mass Market Paperback]","['First published July 8, 1999']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['435'],"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",4215031,84959,4.58,"{'5': '2,892,322', '4': '970,190', '3': '287,7..."
4,6,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Goblet, of, Fire]","[It, is, the, summer, holidays, and, soon, Har...","[734 pages, Paperback]","['First published July 8, 2000']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['734'],"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",3718209,69961,4.57,"{'5': '2,500,070', '4': '899,496', '3': '259,7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16220,208877606,https://images-na.ssl-images-amazon.com/images...,[Finistère],"[The, 1920s., When, wealthy, American, adolesc...","[316 pages, Paperback]","['First published January 1, 1951']",https://www.goodreads.com/author/show/151154.F...,Fritz Peters,['316'],"['Fiction', 'LGBT', 'Queer', 'Classics', 'Gay'...",129,22,3.77,"{'5': '36', '4': '41', '3': '41', '2': '8', '1..."
16221,208877648,https://images-na.ssl-images-amazon.com/images...,"[The, Descent]","[Set, in, the, 1950s,, The, Descent, asks, the...","[268 pages, Paperback]","['First published January 1, 1952']",https://www.goodreads.com/author/show/151154.F...,Fritz Peters,['268'],['Fiction'],4,0,4.75,"{'5': '3', '4': '1', '3': '0', '2': '0', '1': ..."
16222,209251042,https://images-na.ssl-images-amazon.com/images...,"[FDR, Unmasked:, 73, Years, of, Medical, Cover...","[THE, HIDDEN, ILLNESSES, THAT, SHAPED, FDR’S, ...","[316 pages, Paperback]","['Published February 27, 2024']",https://www.goodreads.com/author/show/2991326....,Steven Lomazow,['316'],"['Drama', 'Novels', 'Contemporary']",986,11,4.32,"{'5': '469', '4': '431', '3': '38', '2': '33',..."
16223,209441121,https://images-na.ssl-images-amazon.com/images...,"[Code, Yellow, in, Gretna, Green]","[In, Gateway, terminology,, a, ""Code, Yellow"",...","[776 pages, Kindle Edition]","['Published March 28, 2024']",https://www.goodreads.com/author/show/22515164...,Linzi Day,['776'],"['Science Fiction Fantasy', 'Fantasy', 'Fictio...",1109,106,4.61,"{'5': '764', '4': '266', '3': '74', '2': '4', ..."
16224,209607645,https://images-na.ssl-images-amazon.com/images...,"[Shadow's, Siege]","[Shadow, Island, is, under, siege.Just, a, few...","[254 pages, Kindle Edition]","['Published April 25, 2024']",https://www.goodreads.com/author/show/19007338...,Mary Stone,['254'],"['Drama', 'Novels', 'Crime', 'Thriller', 'Susp...",1271,37,4.64,"{'5': '914', '4': '277', '3': '70', '2': '5', ..."

In [72]:
df["publication_info"][0]

"['First published July 16, 2005']"

In [73]:
def change_info(x):
    lis = []
    for i in x:
        lis.append(i.split())
    return lis

In [74]:
df["publication_info"] = df["publication_info"].apply(ast.literal_eval)
df["publication_info"][0]

['First published July 16, 2005']

In [75]:
df["publication_info"] = df["publication_info"].apply(change_info)
df["publication_info"][0]

[['First', 'published', 'July', '16,', '2005']]

In [76]:
df["publication_info"] = df["publication_info"].apply(change)
df["publication_info"][0]

['First', 'published', 'July', '16,', '2005']

In [77]:
df.columns

Index(['book_id', 'cover_image_uri', 'book_title', 'book_details', 'format',
       'publication_info', 'authorlink', 'author', 'num_pages', 'genres',
       'num_ratings', 'num_reviews', 'average_rating', 'rating_distribution'],
      dtype='object')

In [78]:
df["authorlink"][0]

'https://www.goodreads.com/author/show/1077326.J_K_Rowling'

In [79]:
df["author"][0]

'J.K. Rowling'

In [80]:
df["author"] = df["author"].apply(lambda x: [x])
df["author"][0]

['J.K. Rowling']

In [81]:
df["genres"]

0        ['Fantasy', 'Young Adult', 'Fiction', 'Magic',...
1        ['Young Adult', 'Fiction', 'Magic', 'Childrens...
2        ['Fantasy', 'Fiction', 'Young Adult', 'Magic',...
3        ['Fantasy', 'Fiction', 'Young Adult', 'Magic',...
4        ['Fantasy', 'Young Adult', 'Fiction', 'Magic',...
                               ...
16220    ['Fiction', 'LGBT', 'Queer', 'Classics', 'Gay'...
16221                                          ['Fiction']
16222                  ['Drama', 'Novels', 'Contemporary']
16223    ['Science Fiction Fantasy', 'Fantasy', 'Fictio...
16224    ['Drama', 'Novels', 'Crime', 'Thriller', 'Susp...
Name: genres, Length: 16177, dtype: object

In [82]:
df["num_pages"] = df["num_pages"].apply(ast.literal_eval)
df["num_pages"][0]

['652']

In [83]:
df["genres"] = df["genres"].apply(ast.literal_eval)
df["genres"][0]

['Fantasy',
 'Young Adult',
 'Fiction',
 'Magic',
 'Childrens',
 'Audiobook',
 'Adventure']

In [84]:
df.columns

Index(['book_id', 'cover_image_uri', 'book_title', 'book_details', 'format',
       'publication_info', 'authorlink', 'author', 'num_pages', 'genres',
       'num_ratings', 'num_reviews', 'average_rating', 'rating_distribution'],
      dtype='object')

In [85]:
df["tags"] = df["book_details"]+ df["book_title"] + df["format"] + df["publication_info"] + df["author"] + df["num_pages"] + df["genres"]

In [86]:
df

,book_id,cover_image_uri,book_title,book_details,format,publication_info,authorlink,author,num_pages,genres,num_ratings,num_reviews,average_rating,rating_distribution,tags
0,1,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Half-Blood, Prince]","[It, is, the, middle, of, the, summer,, but, t...","[652 pages, Paperback]","[First, published, July, 16,, 2005]",https://www.goodreads.com/author/show/1077326....,[J.K. Rowling],[652],"[Fantasy, Young Adult, Fiction, Magic, Childre...",3292516,58398,4.58,"{'5': '2,244,154', '4': '775,028', '3': '219,8...","[It, is, the, middle, of, the, summer,, but, t..."
1,2,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Order, of, the, Phoe...","[Harry, Potter, is, about, to, start, his, fif...","[912 pages, Paperback]","[First, published, June, 21,, 2003]",https://www.goodreads.com/author/show/1077326....,[J.K. Rowling],[912],"[Young Adult, Fiction, Magic, Childrens, Audio...",3401709,64300,4.50,"{'5': '2,178,760', '4': '856,178', '3': '293,2...","[Harry, Potter, is, about, to, start, his, fif..."
2,3,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Sorcerer's, Stone]","[Harry, Potter, has, no, idea, how, famous, he...","[309 pages, Hardcover]","[First, published, June, 26,, 1997]",https://www.goodreads.com/author/show/1077326....,[J.K. Rowling],[309],"[Fantasy, Fiction, Young Adult, Magic, Childre...",10116247,163493,4.47,"{'5': '6,544,542', '4': '2,348,390', '3': '856...","[Harry, Potter, has, no, idea, how, famous, he..."
3,5,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Prisoner, of, Azkaban]","[Harry, Potter,, along, with, his, best, frien...","[435 pages, Mass Market Paperback]","[First, published, July, 8,, 1999]",https://www.goodreads.com/author/show/1077326....,[J.K. Rowling],[435],"[Fantasy, Fiction, Young Adult, Magic, Childre...",4215031,84959,4.58,"{'5': '2,892,322', '4': '970,190', '3': '287,7...","[Harry, Potter,, along, with, his, best, frien..."
4,6,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Goblet, of, Fire]","[It, is, the, summer, holidays, and, soon, Har...","[734 pages, Paperback]","[First, published, July, 8,, 2000]",https://www.goodreads.com/author/show/1077326....,[J.K. Rowling],[734],"[Fantasy, Young Adult, Fiction, Magic, Childre...",3718209,69961,4.57,"{'5': '2,500,070', '4': '899,496', '3': '259,7...","[It, is, the, summer, holidays, and, soon, Har..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16220,208877606,https://images-na.ssl-images-amazon.com/images...,[Finistère],"[The, 1920s., When, wealthy, American, adolesc...","[316 pages, Paperback]","[First, published, January, 1,, 1951]",https://www.goodreads.com/author/show/151154.F...,[Fritz Peters],[316],"[Fiction, LGBT, Queer, Classics, Gay, Gay Fict...",129,22,3.77,"{'5': '36', '4': '41', '3': '41', '2': '8', '1...","[The, 1920s., When, wealthy, American, adolesc..."
16221,208877648,https://images-na.ssl-images-amazon.com/images...,"[The, Descent]","[Set, in, the, 1950s,, The, Descent, asks, the...","[268 pages, Paperback]","[First, published, January, 1,, 1952]",https://www.goodreads.com/author/show/151154.F...,[Fritz Peters],[268],[Fiction],4,0,4.75,"{'5': '3', '4': '1', '3': '0', '2': '0', '1': ...","[Set, in, the, 1950s,, The, Descent, asks, the..."
16222,209251042,https://images-na.ssl-images-amazon.com/images...,"[FDR, Unmasked:, 73, Years, of, Medical, Cover...","[THE, HIDDEN, ILLNESSES, THAT, SHAPED, FDR’S, ...","[316 pages, Paperback]","[Published, February, 27,, 2024]",https://www.goodreads.com/author/show/2991326....,[Steven Lomazow],[316],"[Drama, Novels, Contemporary]",986,11,4.32,"{'5': '469', '4': '431', '3': '38', '2': '33',...","[THE, HIDDEN, ILLNESSES, THAT, SHAPED, FDR’S, ..."
16223,209441121,https://images-na.ssl-images-amazon.com/images...,"[Code, Yellow, in, Gretna, Green]","[In, Gateway, terminology,, a, ""Code, Yellow"",...","[776 pages, Kindle Edition]","[Published, March, 28,, 2024]",https://www.goodreads.com/author/show/22515164...,[Linzi Day],[776],"[Science Fiction Fantasy, Fantasy, Fiction, Ep...",1109,106,4.61,"{'5': '764', '4': '266', '3': '74', '2': '4', ...","[In, Gateway, terminology,, a, ""Code, Yellow"",..."
16224,209607645,https://images-na.ssl-images-amazon.com/images...,"[Shadow's, Siege]","[Shadow, Island, is, under, siege.Just, a, few...","[254 pages, Kindle Edition]","[Published, April, 25,, 2024]",https://www.goodreads.com/author/show/19007338...,[Mary Stone],[254],"[Drama, Novels, Crime, Thriller, Suspense]",1271,37,4.64,"{'5': '914', '4': '277', '3': '70', '2': '5', ...","[Shadow, Island, is, under, siege.Just, a, few..."

In [87]:
df.drop(columns=['book_id',  'book_details', 'format',
       'publication_info', 'authorlink' , 'num_pages', 'genres',
       'num_ratings', 'num_reviews', 'average_rating', 'rating_distribution'],inplace=True)

In [88]:
df["tags"][0]

['It',
 'is',
 'the',
 'middle',
 'of',
 'the',
 'summer,',
 'but',
 'there',
 'is',
 'an',
 'unseasonal',
 'mist',
 'pressing',
 'against',
 'the',
 'windowpanes.',
 'Harry',
 'Potter',
 'is',
 'waiting',
 'nervously',
 'in',
 'his',
 'bedroom',
 'at',
 'the',
 "Dursleys'",
 'house',
 'in',
 'Privet',
 'Drive',
 'for',
 'a',
 'visit',
 'from',
 'Professor',
 'Dumbledore',
 'himself.',
 'One',
 'of',
 'the',
 'last',
 'times',
 'he',
 'saw',
 'the',
 'Headmaster,',
 'he',
 'was',
 'in',
 'a',
 'fierce',
 'one-to-one',
 'duel',
 'with',
 'Lord',
 'Voldemort,',
 'and',
 'Harry',
 "can't",
 'quite',
 'believe',
 'that',
 'Professor',
 'Dumbledore',
 'will',
 'actually',
 'appear',
 'at',
 'the',
 "Dursleys'",
 'of',
 'all',
 'places.',
 'Why',
 'is',
 'the',
 'Professor',
 'coming',
 'to',
 'visit',
 'him',
 'now?',
 'What',
 'is',
 'it',
 'that',
 'cannot',
 'wait',
 'until',
 'Harry',
 'returns',
 'to',
 'Hogwarts',
 'in',
 'a',
 'few',
 "weeks'",
 'time?',
 "Harry's",
 'sixth',
 'year',
 'at',
 'Hogwarts',
 'has',
 'already',
 'got',
 'off',
 'to',
 'an',
 'unusual',
 'start,',
 'as',
 'the',
 'worlds',
 'of',
 'Muggle',
 'and',
 'magic',
 'start',
 'to',
 'intertwine...',
 'Harry',
 'Potter',
 'and',
 'the',
 'Half-Blood',
 'Prince',
 '652 pages',
 ' Paperback',
 'First',
 'published',
 'July',
 '16,',
 '2005',
 'J.K. Rowling',
 '652',
 'Fantasy',
 'Young Adult',
 'Fiction',
 'Magic',
 'Childrens',
 'Audiobook',
 'Adventure']

In [89]:
df["tags"] = df["tags"].apply(lambda x: " ".join([i for i in x if i is not None]))

In [90]:
df["tags"][0]

"It is the middle of the summer, but there is an unseasonal mist pressing against the windowpanes. Harry Potter is waiting nervously in his bedroom at the Dursleys' house in Privet Drive for a visit from Professor Dumbledore himself. One of the last times he saw the Headmaster, he was in a fierce one-to-one duel with Lord Voldemort, and Harry can't quite believe that Professor Dumbledore will actually appear at the Dursleys' of all places. Why is the Professor coming to visit him now? What is it that cannot wait until Harry returns to Hogwarts in a few weeks' time? Harry's sixth year at Hogwarts has already got off to an unusual start, as the worlds of Muggle and magic start to intertwine... Harry Potter and the Half-Blood Prince 652 pages  Paperback First published July 16, 2005 J.K. Rowling 652 Fantasy Young Adult Fiction Magic Childrens Audiobook Adventure"

In [91]:
df.isna().sum()

cover_image_uri    0
book_title         0
author             0
tags               0
dtype: int64

In [93]:
import nltk
from nltk.stem.porter import PorterStemmer

nltk.download('punkt')  # for tokenizing

stemmer = PorterStemmer()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Microsoft\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [94]:
def stem_text(text):
    return " ".join([stemmer.stem(word) for word in nltk.word_tokenize(text.lower())])

df['tags'] = df['tags'].apply(stem_text)

In [95]:
from nltk.corpus import stopwords

import nltk
# nltk.download('stopwords')  # only first time

stop_words = stopwords.words("english")  # ✅ correct

In [96]:
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer

nltk.download('stopwords')
stop_words = stopwords.words('english')

cv = CountVectorizer(stop_words=stop_words)
X = cv.fit_transform(df["tags"])

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Microsoft\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [97]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(X,dense_output=False)

print(similarity_matrix.toarray())

[[1.         0.43825049 0.37888574 ... 0.08303989 0.06847067 0.05532551]
 [0.43825049 1.         0.57739023 ... 0.26053558 0.06137858 0.04959498]
 [0.37888574 0.57739023 1.         ... 0.19113547 0.07004491 0.02263901]
 ...
 [0.08303989 0.26053558 0.19113547 ... 1.         0.03837913 0.08140391]
 [0.06847067 0.06137858 0.07004491 ... 0.03837913 1.         0.08182457]
 [0.05532551 0.04959498 0.02263901 ... 0.08140391 0.08182457 1.        ]]

In [98]:
df["book_title"] = df["book_title"].apply(lambda x: " ".join(x))

In [99]:
movie_index = {book: i for i, book in enumerate(df['book_title'])}

In [105]:
def recommend(book_title, top_n=5):
    # Check if movie exists
    idx = movie_index.get(book_title)
    if idx is None:
        return f"Movie '{book_title}' not found."

    # Get similarity scores for this movie
    sim_scores = list(enumerate(similarity_matrix[idx].toarray()[0]))  # convert sparse row to array

    # Sort by similarity (highest first) and skip itself
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:top_n+1]

    # Get movie indices
    book_indices = [i[0] for i in sim_scores]

    # Return movie names
    return df[['book_title','author']].iloc[book_indices].values.tolist()

In [106]:
recommend("The Midnight Library",10)

[['The Midnight Library', ['Matt Haig']],
 ['Little Bee', ['Chris Cleave']],
 ['Shadowmancer', ['G.P. Taylor']],
 ['Wool', ['Hugh Howey']],
 ['Whipping Star', ['Frank Herbert']],
 ['The Obelisk Gate', ['N.K. Jemisin']],
 ['The First Days', ['Rhiannon Frater']],
 ['The First Fifteen Lives of Harry August', ['Claire North']],
 ['Peace', ['Gene Wolfe']],
 ['Last and First Men/Star Maker', ['Olaf Stapledon']]]

In [ ]:
import pickle
# Save CountVectorizer
with open('count_vectorizer.pkl', 'wb') as f:
    pickle.dump(cv, f)