# Loading data set

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("dataset\Book_Details.csv")
df

<>:4: SyntaxWarning: "\B" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\B"? A raw string is also an option.
<>:4: SyntaxWarning: "\B" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\B"? A raw string is also an option.
C:\Users\Alvi\AppData\Local\Temp\ipykernel_13180\2734782594.py:4: SyntaxWarning: "\B" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\B"? A raw string is also an option.
  df = pd.read_csv("dataset\Book_Details.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'dataset\\Book_Details.csv'

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16225 entries, 0 to 16224
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           16225 non-null  int64
 1   book_id              16225 non-null  int64
 2   cover_image_uri      16225 non-null  str
 3   book_title           16225 non-null  str
 4   book_details         16177 non-null  str
 5   format               16225 non-null  str
 6   publication_info     16225 non-null  str
 7   authorlink           16225 non-null  str
 8   author               16225 non-null  str
 9   num_pages            16225 non-null  str
 10  genres               16225 non-null  str
 11  num_ratings          16225 non-null  int64
 12  num_reviews          16225 non-null  int64
 13  average_rating       16225 non-null  float64
 14  rating_distribution  16225 non-null  str
dtypes: float64(1), int64(4), str(10)
memory usage: 22.3 MB

In [ ]:
df.isna().sum()

Unnamed: 0              0
book_id                 0
cover_image_uri         0
book_title              0
book_details           48
format                  0
publication_info        0
authorlink              0
author                  0
num_pages               0
genres                  0
num_ratings             0
num_reviews             0
average_rating          0
rating_distribution     0
dtype: int64

In [ ]:
df.dropna(inplace=True)
df.isna().sum()

Unnamed: 0             0
book_id                0
cover_image_uri        0
book_title             0
book_details           0
format                 0
publication_info       0
authorlink             0
author                 0
num_pages              0
genres                 0
num_ratings            0
num_reviews            0
average_rating         0
rating_distribution    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.columns

Index(['Unnamed: 0', 'book_id', 'cover_image_uri', 'book_title',
       'book_details', 'format', 'publication_info', 'authorlink', 'author',
       'num_pages', 'genres', 'num_ratings', 'num_reviews', 'average_rating',
       'rating_distribution'],
      dtype='str')

In [ ]:
df.drop(columns="Unnamed: 0",inplace=True)
df

,book_id,cover_image_uri,book_title,book_details,format,publication_info,authorlink,author,num_pages,genres,num_ratings,num_reviews,average_rating,rating_distribution
0,1,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Half-Blood Prince,"It is the middle of the summer, but there is a...","['652 pages, Paperback']","['First published July 16, 2005']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['652'],"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",3292516,58398,4.58,"{'5': '2,244,154', '4': '775,028', '3': '219,8..."
1,2,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Order of the Phoenix,Harry Potter is about to start his fifth year ...,"['912 pages, Paperback']","['First published June 21, 2003']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['912'],"['Young Adult', 'Fiction', 'Magic', 'Childrens...",3401709,64300,4.50,"{'5': '2,178,760', '4': '856,178', '3': '293,2..."
2,3,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Sorcerer's Stone,Harry Potter has no idea how famous he is. Tha...,"['309 pages, Hardcover']","['First published June 26, 1997']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['309'],"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",10116247,163493,4.47,"{'5': '6,544,542', '4': '2,348,390', '3': '856..."
3,5,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Prisoner of Azkaban,"Harry Potter, along with his best friends, Ron...","['435 pages, Mass Market Paperback']","['First published July 8, 1999']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['435'],"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",4215031,84959,4.58,"{'5': '2,892,322', '4': '970,190', '3': '287,7..."
4,6,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Goblet of Fire,It is the summer holidays and soon Harry Potte...,"['734 pages, Paperback']","['First published July 8, 2000']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['734'],"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",3718209,69961,4.57,"{'5': '2,500,070', '4': '899,496', '3': '259,7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16220,208877606,https://images-na.ssl-images-amazon.com/images...,Finistère,The 1920s. When wealthy American adolescent Ma...,"['316 pages, Paperback']","['First published January 1, 1951']",https://www.goodreads.com/author/show/151154.F...,Fritz Peters,['316'],"['Fiction', 'LGBT', 'Queer', 'Classics', 'Gay'...",129,22,3.77,"{'5': '36', '4': '41', '3': '41', '2': '8', '1..."
16221,208877648,https://images-na.ssl-images-amazon.com/images...,The Descent,"Set in the 1950s, The Descent asks the questio...","['268 pages, Paperback']","['First published January 1, 1952']",https://www.goodreads.com/author/show/151154.F...,Fritz Peters,['268'],['Fiction'],4,0,4.75,"{'5': '3', '4': '1', '3': '0', '2': '0', '1': ..."
16222,209251042,https://images-na.ssl-images-amazon.com/images...,FDR Unmasked: 73 Years of Medical Cover-ups Th...,THE HIDDEN ILLNESSES THAT SHAPED FDR’S LIFE AN...,"['316 pages, Paperback']","['Published February 27, 2024']",https://www.goodreads.com/author/show/2991326....,Steven Lomazow,['316'],"['Drama', 'Novels', 'Contemporary']",986,11,4.32,"{'5': '469', '4': '431', '3': '38', '2': '33',..."
16223,209441121,https://images-na.ssl-images-amazon.com/images...,Code Yellow in Gretna Green,"In Gateway terminology, a ""Code Yellow"" signif...","['776 pages, Kindle Edition']","['Published March 28, 2024']",https://www.goodreads.com/author/show/22515164...,Linzi Day,['776'],"['Science Fiction Fantasy', 'Fantasy', 'Fictio...",1109,106,4.61,"{'5': '764', '4': '266', '3': '74', '2': '4', ..."
16224,209607645,https://images-na.ssl-images-amazon.com/images...,Shadow's Siege,Shadow Island is under siege.Just a few short ...,"['254 pages, Kindle Edition']","['Published April 25, 2024']",https://www.goodreads.com/author/show/19007338...,Mary Stone,['254'],"['Drama', 'Novels', 'Crime', 'Thriller', 'Susp...",1271,37,4.64,"{'5': '914', '4': '277', '3': '70', '2': '5', ..."

# Text Preprocessing

In [ ]:
import string

english_letters = set(string.ascii_letters)

def has_non_english_letter(text):
    if pd.isna(text):
        return False

    for char in str(text):
        if char.isalpha() and char not in english_letters:
            return True

    return False

In [ ]:
mask = df["book_title"].apply(has_non_english_letter)

df = df[~mask].copy()

In [ ]:
df["book_title"][0]

'Harry Potter and the Half-Blood Prince'

In [ ]:
df["book_title"] = df["book_title"].apply(lambda x: x.split())
df["book_title"][0]

['Harry', 'Potter', 'and', 'the', 'Half-Blood', 'Prince']

In [ ]:
df.columns

Index(['book_id', 'cover_image_uri', 'book_title', 'book_details', 'format',
       'publication_info', 'authorlink', 'author', 'num_pages', 'genres',
       'num_ratings', 'num_reviews', 'average_rating', 'rating_distribution'],
      dtype='str')

In [ ]:
df["book_details"][0]

"It is the middle of the summer, but there is an unseasonal mist pressing against the windowpanes. Harry Potter is waiting nervously in his bedroom at the Dursleys' house in Privet Drive for a visit from Professor Dumbledore himself. One of the last times he saw the Headmaster, he was in a fierce one-to-one duel with Lord Voldemort, and Harry can't quite believe that Professor Dumbledore will actually appear at the Dursleys' of all places. Why is the Professor coming to visit him now? What is it that cannot wait until Harry returns to Hogwarts in a few weeks' time? Harry's sixth year at Hogwarts has already got off to an unusual start, as the worlds of Muggle and magic start to intertwine..."

In [ ]:
df["book_details"] = df["book_details"].apply(lambda x: x.split())
df["book_details"][0]

['It',
 'is',
 'the',
 'middle',
 'of',
 'the',
 'summer,',
 'but',
 'there',
 'is',
 'an',
 'unseasonal',
 'mist',
 'pressing',
 'against',
 'the',
 'windowpanes.',
 'Harry',
 'Potter',
 'is',
 'waiting',
 'nervously',
 'in',
 'his',
 'bedroom',
 'at',
 'the',
 "Dursleys'",
 'house',
 'in',
 'Privet',
 'Drive',
 'for',
 'a',
 'visit',
 'from',
 'Professor',
 'Dumbledore',
 'himself.',
 'One',
 'of',
 'the',
 'last',
 'times',
 'he',
 'saw',
 'the',
 'Headmaster,',
 'he',
 'was',
 'in',
 'a',
 'fierce',
 'one-to-one',
 'duel',
 'with',
 'Lord',
 'Voldemort,',
 'and',
 'Harry',
 "can't",
 'quite',
 'believe',
 'that',
 'Professor',
 'Dumbledore',
 'will',
 'actually',
 'appear',
 'at',
 'the',
 "Dursleys'",
 'of',
 'all',
 'places.',
 'Why',
 'is',
 'the',
 'Professor',
 'coming',
 'to',
 'visit',
 'him',
 'now?',
 'What',
 'is',
 'it',
 'that',
 'cannot',
 'wait',
 'until',
 'Harry',
 'returns',
 'to',
 'Hogwarts',
 'in',
 'a',
 'few',
 "weeks'",
 'time?',
 "Harry's",
 'sixth',
 'year',
 'at',
 'Hogwarts',
 'has',
 'already',
 'got',
 'off',
 'to',
 'an',
 'unusual',
 'start,',
 'as',
 'the',
 'worlds',
 'of',
 'Muggle',
 'and',
 'magic',
 'start',
 'to',
 'intertwine...']

In [ ]:
df["format"][0]

"['652 pages, Paperback']"

In [ ]:
import ast

In [ ]:
df["format"] = df["format"].apply(ast.literal_eval)
df["format"][3]

['435 pages, Mass Market Paperback']

In [ ]:

def change_format(x):
    lis= []
    for i in x:
        lis.append(i.split(","))
    return lis

In [ ]:
df["format"] = df["format"].apply(change_format)
df["format"][0]

[['652 pages', ' Paperback']]

In [ ]:
def change(x):
    lis = []
    for i in x:
        for j in i:
            lis.append(j)
    return lis
df["format"] = df["format"].apply(change)

In [ ]:
df["format"][0]

['652 pages', ' Paperback']

In [ ]:
df

,book_id,cover_image_uri,book_title,book_details,format,publication_info,authorlink,author,num_pages,genres,num_ratings,num_reviews,average_rating,rating_distribution
0,1,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Half-Blood, Prince]","[It, is, the, middle, of, the, summer,, but, t...","[652 pages, Paperback]","['First published July 16, 2005']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['652'],"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",3292516,58398,4.58,"{'5': '2,244,154', '4': '775,028', '3': '219,8..."
1,2,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Order, of, the, Phoe...","[Harry, Potter, is, about, to, start, his, fif...","[912 pages, Paperback]","['First published June 21, 2003']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['912'],"['Young Adult', 'Fiction', 'Magic', 'Childrens...",3401709,64300,4.50,"{'5': '2,178,760', '4': '856,178', '3': '293,2..."
2,3,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Sorcerer's, Stone]","[Harry, Potter, has, no, idea, how, famous, he...","[309 pages, Hardcover]","['First published June 26, 1997']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['309'],"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",10116247,163493,4.47,"{'5': '6,544,542', '4': '2,348,390', '3': '856..."
3,5,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Prisoner, of, Azkaban]","[Harry, Potter,, along, with, his, best, frien...","[435 pages, Mass Market Paperback]","['First published July 8, 1999']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['435'],"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",4215031,84959,4.58,"{'5': '2,892,322', '4': '970,190', '3': '287,7..."
4,6,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Goblet, of, Fire]","[It, is, the, summer, holidays, and, soon, Har...","[734 pages, Paperback]","['First published July 8, 2000']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['734'],"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",3718209,69961,4.57,"{'5': '2,500,070', '4': '899,496', '3': '259,7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16219,208567667,https://images-na.ssl-images-amazon.com/images...,"[The, Art, of, Avoiding, Your, Alpha]","[My, soulmate, bought, me, a, sugar, cookie…, ...","[221 pages, Kindle Edition]","['Published March 13, 2024']",https://www.goodreads.com/author/show/20827982...,Lola Glass,['221'],"['Science Fiction Fantasy', 'Fantasy', 'Novels...",1515,88,4.01,"{'5': '549', '4': '527', '3': '357', '2': '68'..."
16221,208877648,https://images-na.ssl-images-amazon.com/images...,"[The, Descent]","[Set, in, the, 1950s,, The, Descent, asks, the...","[268 pages, Paperback]","['First published January 1, 1952']",https://www.goodreads.com/author/show/151154.F...,Fritz Peters,['268'],['Fiction'],4,0,4.75,"{'5': '3', '4': '1', '3': '0', '2': '0', '1': ..."
16222,209251042,https://images-na.ssl-images-amazon.com/images...,"[FDR, Unmasked:, 73, Years, of, Medical, Cover...","[THE, HIDDEN, ILLNESSES, THAT, SHAPED, FDR’S, ...","[316 pages, Paperback]","['Published February 27, 2024']",https://www.goodreads.com/author/show/2991326....,Steven Lomazow,['316'],"['Drama', 'Novels', 'Contemporary']",986,11,4.32,"{'5': '469', '4': '431', '3': '38', '2': '33',..."
16223,209441121,https://images-na.ssl-images-amazon.com/images...,"[Code, Yellow, in, Gretna, Green]","[In, Gateway, terminology,, a, ""Code, Yellow"",...","[776 pages, Kindle Edition]","['Published March 28, 2024']",https://www.goodreads.com/author/show/22515164...,Linzi Day,['776'],"['Science Fiction Fantasy', 'Fantasy', 'Fictio...",1109,106,4.61,"{'5': '764', '4': '266', '3': '74', '2': '4', ..."
16224,209607645,https://images-na.ssl-images-amazon.com/images...,"[Shadow's, Siege]","[Shadow, Island, is, under, siege.Just, a, few...","[254 pages, Kindle Edition]","['Published April 25, 2024']",https://www.goodreads.com/author/show/19007338...,Mary Stone,['254'],"['Drama', 'Novels', 'Crime', 'Thriller', 'Susp...",1271,37,4.64,"{'5': '914', '4': '277', '3': '70', '2': '5', ..."

In [ ]:
df["publication_info"][0]

"['First published July 16, 2005']"

In [ ]:
def change_info(x):
    lis = []
    for i in x:
        lis.append(i.split())
    return lis

In [ ]:
df["publication_info"] = df["publication_info"].apply(ast.literal_eval)
df["publication_info"][0]

['First published July 16, 2005']

In [ ]:
df["publication_info"] = df["publication_info"].apply(change_info)
df["publication_info"][0]

[['First', 'published', 'July', '16,', '2005']]

In [ ]:
df["publication_info"] = df["publication_info"].apply(change)
df["publication_info"][0]

['First', 'published', 'July', '16,', '2005']

In [ ]:
df.columns

Index(['book_id', 'cover_image_uri', 'book_title', 'book_details', 'format',
       'publication_info', 'authorlink', 'author', 'num_pages', 'genres',
       'num_ratings', 'num_reviews', 'average_rating', 'rating_distribution'],
      dtype='str')

In [ ]:
df["authorlink"][0]

'https://www.goodreads.com/author/show/1077326.J_K_Rowling'

In [ ]:
df["author"][0]

'J.K. Rowling'

In [ ]:
df["author"] = df["author"].apply(lambda x: [x])
df["author"][0]

['J.K. Rowling']

In [ ]:
df["genres"]

0        ['Fantasy', 'Young Adult', 'Fiction', 'Magic',...
1        ['Young Adult', 'Fiction', 'Magic', 'Childrens...
2        ['Fantasy', 'Fiction', 'Young Adult', 'Magic',...
3        ['Fantasy', 'Fiction', 'Young Adult', 'Magic',...
4        ['Fantasy', 'Young Adult', 'Fiction', 'Magic',...
                               ...
16219    ['Science Fiction Fantasy', 'Fantasy', 'Novels...
16221                                          ['Fiction']
16222                  ['Drama', 'Novels', 'Contemporary']
16223    ['Science Fiction Fantasy', 'Fantasy', 'Fictio...
16224    ['Drama', 'Novels', 'Crime', 'Thriller', 'Susp...
Name: genres, Length: 15749, dtype: str

In [ ]:
df["num_pages"] = df["num_pages"].apply(ast.literal_eval)
df["num_pages"][0]

['652']

In [ ]:
df["genres"] = df["genres"].apply(ast.literal_eval)
df["genres"][0]

['Fantasy',
 'Young Adult',
 'Fiction',
 'Magic',
 'Childrens',
 'Audiobook',
 'Adventure']

In [ ]:
df.columns

Index(['book_id', 'cover_image_uri', 'book_title', 'book_details', 'format',
       'publication_info', 'authorlink', 'author', 'num_pages', 'genres',
       'num_ratings', 'num_reviews', 'average_rating', 'rating_distribution'],
      dtype='str')

In [ ]:
df["tags"] = df["book_details"]+ df["book_title"] + df["publication_info"] + (df["author"]*4)  + (df["genres"]*3)

In [ ]:
df

,book_id,cover_image_uri,book_title,book_details,format,publication_info,authorlink,author,num_pages,genres,num_ratings,num_reviews,average_rating,rating_distribution,tags
0,1,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Half-Blood, Prince]","[It, is, the, middle, of, the, summer,, but, t...","[652 pages, Paperback]","[First, published, July, 16,, 2005]",https://www.goodreads.com/author/show/1077326....,[J.K. Rowling],[652],"[Fantasy, Young Adult, Fiction, Magic, Childre...",3292516,58398,4.58,"{'5': '2,244,154', '4': '775,028', '3': '219,8...","[It, is, the, middle, of, the, summer,, but, t..."
1,2,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Order, of, the, Phoe...","[Harry, Potter, is, about, to, start, his, fif...","[912 pages, Paperback]","[First, published, June, 21,, 2003]",https://www.goodreads.com/author/show/1077326....,[J.K. Rowling],[912],"[Young Adult, Fiction, Magic, Childrens, Audio...",3401709,64300,4.50,"{'5': '2,178,760', '4': '856,178', '3': '293,2...","[Harry, Potter, is, about, to, start, his, fif..."
2,3,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Sorcerer's, Stone]","[Harry, Potter, has, no, idea, how, famous, he...","[309 pages, Hardcover]","[First, published, June, 26,, 1997]",https://www.goodreads.com/author/show/1077326....,[J.K. Rowling],[309],"[Fantasy, Fiction, Young Adult, Magic, Childre...",10116247,163493,4.47,"{'5': '6,544,542', '4': '2,348,390', '3': '856...","[Harry, Potter, has, no, idea, how, famous, he..."
3,5,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Prisoner, of, Azkaban]","[Harry, Potter,, along, with, his, best, frien...","[435 pages, Mass Market Paperback]","[First, published, July, 8,, 1999]",https://www.goodreads.com/author/show/1077326....,[J.K. Rowling],[435],"[Fantasy, Fiction, Young Adult, Magic, Childre...",4215031,84959,4.58,"{'5': '2,892,322', '4': '970,190', '3': '287,7...","[Harry, Potter,, along, with, his, best, frien..."
4,6,https://images-na.ssl-images-amazon.com/images...,"[Harry, Potter, and, the, Goblet, of, Fire]","[It, is, the, summer, holidays, and, soon, Har...","[734 pages, Paperback]","[First, published, July, 8,, 2000]",https://www.goodreads.com/author/show/1077326....,[J.K. Rowling],[734],"[Fantasy, Young Adult, Fiction, Magic, Childre...",3718209,69961,4.57,"{'5': '2,500,070', '4': '899,496', '3': '259,7...","[It, is, the, summer, holidays, and, soon, Har..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16219,208567667,https://images-na.ssl-images-amazon.com/images...,"[The, Art, of, Avoiding, Your, Alpha]","[My, soulmate, bought, me, a, sugar, cookie…, ...","[221 pages, Kindle Edition]","[Published, March, 13,, 2024]",https://www.goodreads.com/author/show/20827982...,[Lola Glass],[221],"[Science Fiction Fantasy, Fantasy, Novels, Fic...",1515,88,4.01,"{'5': '549', '4': '527', '3': '357', '2': '68'...","[My, soulmate, bought, me, a, sugar, cookie…, ..."
16221,208877648,https://images-na.ssl-images-amazon.com/images...,"[The, Descent]","[Set, in, the, 1950s,, The, Descent, asks, the...","[268 pages, Paperback]","[First, published, January, 1,, 1952]",https://www.goodreads.com/author/show/151154.F...,[Fritz Peters],[268],[Fiction],4,0,4.75,"{'5': '3', '4': '1', '3': '0', '2': '0', '1': ...","[Set, in, the, 1950s,, The, Descent, asks, the..."
16222,209251042,https://images-na.ssl-images-amazon.com/images...,"[FDR, Unmasked:, 73, Years, of, Medical, Cover...","[THE, HIDDEN, ILLNESSES, THAT, SHAPED, FDR’S, ...","[316 pages, Paperback]","[Published, February, 27,, 2024]",https://www.goodreads.com/author/show/2991326....,[Steven Lomazow],[316],"[Drama, Novels, Contemporary]",986,11,4.32,"{'5': '469', '4': '431', '3': '38', '2': '33',...","[THE, HIDDEN, ILLNESSES, THAT, SHAPED, FDR’S, ..."
16223,209441121,https://images-na.ssl-images-amazon.com/images...,"[Code, Yellow, in, Gretna, Green]","[In, Gateway, terminology,, a, ""Code, Yellow"",...","[776 pages, Kindle Edition]","[Published, March, 28,, 2024]",https://www.goodreads.com/author/show/22515164...,[Linzi Day],[776],"[Science Fiction Fantasy, Fantasy, Fiction, Ep...",1109,106,4.61,"{'5': '764', '4': '266', '3': '74', '2': '4', ...","[In, Gateway, terminology,, a, ""Code, Yellow"",..."
16224,209607645,https://images-na.ssl-images-amazon.com/images...,"[Shadow's, Siege]","[Shadow, Island, is, under, siege.Just, a, few...","[254 pages, Kindle Edition]","[Published, April, 25,, 2024]",https://www.goodreads.com/author/show/19007338...,[Mary Stone],[254],"[Drama, Novels, Crime, Thriller, Suspense]",1271,37,4.64,"{'5': '914', '4': '277', '3': '70', '2': '5', ...","[Shadow, Island, is, under, siege.Just, a, few..."

In [ ]:
df.drop(columns=['book_id',   'format',
       'publication_info', 'authorlink' , 'num_pages', 
       'num_ratings', 'num_reviews', 'average_rating', 'rating_distribution'],inplace=True)

In [ ]:
df.isna().sum()

cover_image_uri    0
book_title         0
book_details       0
author             0
genres             0
tags               0
dtype: int64

# Text Vectorization

In [ ]:
def create_book_text(row):
    author = str(row["author"])
    genre = str(row["genres"])
    title = str(row["book_title"])
    details = str(row["book_details"])

    return (
        (author + " ") * 6 +
        (genre + " ") * 3 +
        title + " " +
        details
    )

df["combined_text"] = df.apply(create_book_text, axis=1)

## How TF-IDF Works

**TF-IDF (Term Frequency–Inverse Document Frequency)** converts text into numerical vectors based on how important each word is within a document and across all documents.

### Formula

$$
TF\text{-}IDF = TF \times IDF
$$

* **TF (Term Frequency):** Measures how often a word appears in a document.
* **IDF (Inverse Document Frequency):** Gives lower importance to common words and higher importance to rare words.

In a book recommendation system, TF-IDF converts each book's **author, genre, title, and details** into a numerical vector. These vectors can then be compared using **cosine similarity** to find similar books.

```text
Book Information
      ↓
     TF-IDF
      ↓
Numerical Vectors
      ↓
Cosine Similarity
      ↓
Similar Books
```

By repeating important fields such as **author** and **genre**, their terms can have greater influence on the resulting TF-IDF representation.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1, 2),
    max_features=50000
)

tfidf_matrix = tfidf.fit_transform(df["combined_text"])

### How Cosine Similarity Works

Cosine similarity measures how similar two vectors are by calculating the **angle between them**.

In a book recommendation system, each book is converted into an **embedding vector**. Cosine similarity compares these vectors to find books with similar semantic meaning.

### Formula

$$
\text{Cosine Similarity}(A,B)
=
\frac{A \cdot B}{\|A\|\|B\|}
$$

### Scores

* **1** → Very similar
* **0** → Little or no similarity
* **-1** → Opposite directions

The system calculates similarity between the selected book and other books, then recommends those with the **highest similarity scores**.

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(tfidf_matrix)

print(similarity_matrix)

[[1.00000000e+00 7.78381013e-01 6.07966822e-01 ... 0.00000000e+00
  3.28812382e-02 1.31328304e-03]
 [7.78381013e-01 1.00000000e+00 6.06432319e-01 ... 2.59299352e-03
  1.59852458e-02 6.92765239e-03]
 [6.07966822e-01 6.06432319e-01 1.00000000e+00 ... 3.68413686e-04
  4.23144247e-02 1.76190876e-02]
 ...
 [0.00000000e+00 2.59299352e-03 3.68413686e-04 ... 1.00000000e+00
  1.09951210e-02 5.36478595e-02]
 [3.28812382e-02 1.59852458e-02 4.23144247e-02 ... 1.09951210e-02
  1.00000000e+00 1.42997976e-02]
 [1.31328304e-03 6.92765239e-03 1.76190876e-02 ... 5.36478595e-02
  1.42997976e-02 1.00000000e+00]]

In [ ]:
def keep_top_k(sim_matrix, k=10, exclude_self=True):
    """
    Keep only the top-k similarities for each row.
    
    Parameters
    ----------
    sim_matrix : np.ndarray
        Square similarity matrix (books × books)
    k : int
        Number of most similar books to keep
    exclude_self : bool
        Whether to ignore the diagonal (self-similarity = 1.0)
    
    Returns
    -------
    np.ndarray
        Sparse-like dense matrix with only top-k values kept
    """
    sim = sim_matrix.copy()          # work on a copy
    n = sim.shape[0]

    if exclude_self:
        np.fill_diagonal(sim, -np.inf)   # temporarily kill self-similarity

    # Get the indices of the top-k values in each row
    # argpartition is much faster than full argsort for large matrices
    top_k_idx = np.argpartition(sim, -k, axis=1)[:, -k:]

    # Create a mask of zeros
    mask = np.zeros_like(sim, dtype=bool)

    # Mark the top-k positions as True
    rows = np.arange(n)[:, None]
    mask[rows, top_k_idx] = True

    # Keep original values only where mask is True
    result = np.where(mask, sim_matrix, 0.0)

    # Restore the diagonal if you want self-similarity kept
    if exclude_self:
        np.fill_diagonal(result, 1.0)   # or 0.0 if you prefer

    return result

In [ ]:
similarity_matrix = keep_top_k(similarity_matrix, k=10, exclude_self=True)

In [ ]:
from scipy.sparse import csr_matrix
similarity_sparse = csr_matrix(similarity_matrix)

In [ ]:
similarity_matrix.shape

(15749, 15749)

In [ ]:
# Number of non-zero values in the whole matrix
print("Non-zero entries:", np.count_nonzero(similarity_matrix))

# Non-zero values per row (should be around 11)
# print((similarity_matrix != 0).sum(axis=1).value_counts().head())

Non-zero entries: 173239

In [ ]:
from scipy.sparse import csr_matrix

# Convert the top-10 matrix to sparse format
similarity_matrix = csr_matrix(similarity_matrix)

print("Shape:", similarity_matrix.shape)
print("Non-zero entries:", similarity_matrix.nnz)
print("Density: {:.6%}".format(similarity_matrix.nnz / (16177 * 16177)))

Shape: (15749, 15749)
Non-zero entries: 173239
Density: 0.066199%

In [ ]:
import pickle  

with open('similarity_matrix.pkl', 'wb') as f:
    pickle.dump(similarity_matrix, f)