In [21]:
import numpy as np
import pandas as pd
import re

df = pd.read_csv(r"dataset/Book_Details.csv")
df

,Unnamed: 0,book_id,cover_image_uri,book_title,book_details,format,publication_info,authorlink,author,num_pages,genres,num_ratings,num_reviews,average_rating,rating_distribution
0,0,1,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Half-Blood Prince,"It is the middle of the summer, but there is a...","['652 pages, Paperback']","['First published July 16, 2005']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['652'],"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",3292516,58398,4.58,"{'5': '2,244,154', '4': '775,028', '3': '219,8..."
1,1,2,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Order of the Phoenix,Harry Potter is about to start his fifth year ...,"['912 pages, Paperback']","['First published June 21, 2003']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['912'],"['Young Adult', 'Fiction', 'Magic', 'Childrens...",3401709,64300,4.50,"{'5': '2,178,760', '4': '856,178', '3': '293,2..."
2,2,3,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Sorcerer's Stone,Harry Potter has no idea how famous he is. Tha...,"['309 pages, Hardcover']","['First published June 26, 1997']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['309'],"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",10116247,163493,4.47,"{'5': '6,544,542', '4': '2,348,390', '3': '856..."
3,3,5,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Prisoner of Azkaban,"Harry Potter, along with his best friends, Ron...","['435 pages, Mass Market Paperback']","['First published July 8, 1999']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['435'],"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",4215031,84959,4.58,"{'5': '2,892,322', '4': '970,190', '3': '287,7..."
4,4,6,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Goblet of Fire,It is the summer holidays and soon Harry Potte...,"['734 pages, Paperback']","['First published July 8, 2000']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['734'],"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",3718209,69961,4.57,"{'5': '2,500,070', '4': '899,496', '3': '259,7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16220,16220,208877606,https://images-na.ssl-images-amazon.com/images...,Finistère,The 1920s. When wealthy American adolescent Ma...,"['316 pages, Paperback']","['First published January 1, 1951']",https://www.goodreads.com/author/show/151154.F...,Fritz Peters,['316'],"['Fiction', 'LGBT', 'Queer', 'Classics', 'Gay'...",129,22,3.77,"{'5': '36', '4': '41', '3': '41', '2': '8', '1..."
16221,16221,208877648,https://images-na.ssl-images-amazon.com/images...,The Descent,"Set in the 1950s, The Descent asks the questio...","['268 pages, Paperback']","['First published January 1, 1952']",https://www.goodreads.com/author/show/151154.F...,Fritz Peters,['268'],['Fiction'],4,0,4.75,"{'5': '3', '4': '1', '3': '0', '2': '0', '1': ..."
16222,16222,209251042,https://images-na.ssl-images-amazon.com/images...,FDR Unmasked: 73 Years of Medical Cover-ups Th...,THE HIDDEN ILLNESSES THAT SHAPED FDR’S LIFE AN...,"['316 pages, Paperback']","['Published February 27, 2024']",https://www.goodreads.com/author/show/2991326....,Steven Lomazow,['316'],"['Drama', 'Novels', 'Contemporary']",986,11,4.32,"{'5': '469', '4': '431', '3': '38', '2': '33',..."
16223,16223,209441121,https://images-na.ssl-images-amazon.com/images...,Code Yellow in Gretna Green,"In Gateway terminology, a ""Code Yellow"" signif...","['776 pages, Kindle Edition']","['Published March 28, 2024']",https://www.goodreads.com/author/show/22515164...,Linzi Day,['776'],"['Science Fiction Fantasy', 'Fantasy', 'Fictio...",1109,106,4.61,"{'5': '764', '4': '266', '3': '74', '2': '4', ..."
16224,16224,209607645,https://images-na.ssl-images-amazon.com/images...,Shadow's Siege,Shadow Island is under siege.Just a few short ...,"['254 pages, Kindle Edition']","['Published April 25, 2024']",https://www.goodreads.com/author/show/19007338...,Mary Stone,['254'],"['Drama', 'Novels', 'Crime', 'Thriller', 'Susp...",1271,37,4.64,"{'5': '914', '4': '277', '3': '70', '2': '5', ..."

In [22]:
import string

english_letters = set(string.ascii_letters)

def has_non_english_letter(text):
    if pd.isna(text):
        return False

    for char in str(text):
        if char.isalpha() and char not in english_letters:
            return True

    return False

In [23]:
mask = df["book_title"].apply(has_non_english_letter)

In [24]:
df[mask].head(20)

,Unnamed: 0,book_id,cover_image_uri,book_title,book_details,format,publication_info,authorlink,author,num_pages,genres,num_ratings,num_reviews,average_rating,rating_distribution
158,158,1677,https://images-na.ssl-images-amazon.com/images...,Sobre héroes y tumbas,"Esta es la segunda novela de Ernesto Sabato, q...","['547 pages, Paperback']","['First published January 1, 1961']",https://www.goodreads.com/author/show/33301873...,Ernesto Sabato,['547'],"['Fiction', 'Classics', 'Spanish Literature', ...",12429,711,4.26,"{'5': '6,190', '4': '4,026', '3': '1,675', '2'..."
220,220,2567,https://images-na.ssl-images-amazon.com/images...,Aké: The Years of Childhood,A dazzling memoir of an African childhood from...,"['230 pages, Paperback']","['First published January 1, 1981']",https://www.goodreads.com/author/show/978.Wole...,Wole Soyinka,['230'],"['Africa', 'Nonfiction', 'Nigeria', 'Memoir', ...",1951,181,3.87,"{'5': '611', '4': '692', '3': '482', '2': '119..."
264,264,3300,https://images-na.ssl-images-amazon.com/images...,Inés of My Soul,"Born into a poor family in Spain, Inés, a seam...","['321 pages, Hardcover']","['First published January 1, 2006']",https://www.goodreads.com/author/show/2238.Isa...,Isabel Allende,['321'],"['Historical Fiction', 'Fiction', 'Historical'...",29801,2448,3.98,"{'5': '9,795', '4': '11,696', '3': '6,506', '2..."
273,273,3400,https://images-na.ssl-images-amazon.com/images...,The Troublesome Offspring of Cardinal Guzmán,"With the same ebullient storytelling, luxurian...","['480 pages, Paperback']","['First published January 1, 1992']",https://www.goodreads.com/author/show/2313.Lou...,Louis de Bernières,['480'],"['Fiction', 'Magical Realism', 'Humor', 'Liter...",3666,140,4.13,"{'5': '1,395', '4': '1,524', '3': '598', '2': ..."
663,663,7186,https://images-na.ssl-images-amazon.com/images...,La Dame aux Camélias,"One of the greatest love stories of all time, ...","['256 pages, Paperback']","['First published January 1, 1848']",https://www.goodreads.com/author/show/3186713....,Alexandre Dumas fils,['256'],"['Fiction', 'Romance', 'France', 'Classics', '...",51927,3835,4.03,"{'5': '19,086', '4': '18,991', '3': '10,940', ..."
671,671,7329,https://images-na.ssl-images-amazon.com/images...,Unfinished Tales of Númenor and Middle-Earth,Classic hardback edition of this fascinating c...,"['452 pages, Hardcover']","['First published October 1, 1980']",https://www.goodreads.com/author/show/656983.J...,J.R.R. Tolkien,['452'],"['Fantasy', 'Fiction', 'Classics', 'High Fanta...",39901,1346,4.01,"{'5': '13,791', '4': '15,298', '3': '8,545', '..."
690,690,7629,https://images-na.ssl-images-amazon.com/images...,The Good Soldier Švejk,"In The Good Soldier Švejk, celebrated Czech wr...","['752 pages, Paperback']","['First published March 1, 1921']",https://www.goodreads.com/author/show/1774448....,Jaroslav Hašek,['752'],"['Fiction', 'Classics', 'Czech Literature', 'H...",19202,1361,4.10,"{'5': '8,195', '4': '6,363', '3': '3,328', '2'..."
846,846,9593,https://images-na.ssl-images-amazon.com/images...,Galápagos,Galápagos takes the reader back one million ye...,"['324 pages, Paperback']","['First published January 1, 1985']",https://www.goodreads.com/author/show/2778055....,Kurt Vonnegut Jr.,['324'],"['Fiction', 'Science Fiction', 'Classics', 'Hu...",81680,3864,3.87,"{'5': '22,696', '4': '32,726', '3': '20,560', ..."
998,998,11038,https://images-na.ssl-images-amazon.com/images...,"Henry and June: From ""A Journal of Love"": The ...","Taken from the original, uncensored journals o...","['304 pages, Paperback']","['First published January 1, 1986']",https://www.goodreads.com/author/show/7190.Ana...,Anaïs Nin,['304'],"['Nonfiction', 'Memoir', 'Biography', 'Classic...",12200,866,3.93,"{'5': '4,017', '4': '4,510', '3': '2,696', '2'..."
1005,1005,11208,https://images-na.ssl-images-amazon.com/images...,How the García Girls Lost Their Accents,Uprooted from their family home in the Dominic...,"['286 pages, Paperback']","['First published January 4, 1991']",https://www.goodreads.com/author/show/7277.Jul...,Julia Alvarez,['286'],"['Fiction', 'Historical Fiction', 'Young Adult...",30156,2385,3.63,"{'5': '5,550', '4': '11,459', '3': '10,094', '..."
1151,1151,12749,https://images-na.ssl-images-amazon.com/images...,Du côté de chez Swann,«Et tout d'un coup le souvenir m'est apparu. C...,"['710 pages, Mass Market Paperback']","['First published November 14, 1913']",https://www.goodreads.com/author/show/233619.M...,Marcel Proust,['710'],"['Fiction', 'France', 'Literature', 'French Li...",60445,5414,4.15,"{'5': '29,207', '4': '17,601', '3': '8,642', '..."
1507,1507,17150,https://images-na.ssl-images-amazon.com/images...,My Ántonia,"Through Jim Burden's endearing, smitten voice,...","['219 pages, Paperback']","['First published September 1, 1918']",https://www.goodreads.com/author/show/881203.W...,Willa Cather,['219'],"['Fiction', 'Historical Fiction', 'Classics', ...",138390,9193,3.83,"{'5': '42,157', '4': '49,317', '3': '32,249', ..."
1565,1565,18202,https://images-na.ssl-images-amazon.com/images...,Christianity for Modern Pagans: Pascal's Pensé...,Peter Kreeft believes that Baise Pascal is the...,"['341 pages, Paperback']","['First published October 1, 1993']",https://www.goodreads.com/author/show/4939.Pet...,Peter Kreeft,['341'],"['Philosophy', 'Theology', 'Religion', 'Christ...",592,62,4.38,"{'5': '328', '4': '192', '3': '51', '2': '13',..."
1677,1677,21124,https://images-na.ssl-images-amazon.com/images...,"Le deuxième sexe, I",Nous commencerons par discuter les points de v...,"['408 pages, Mass Market Paperback']","['First published January 1, 1949']",https://www.goodreads.com/author/show/5548.Sim...,Simone de Beauvoir,['408'],"['Feminism', 'Nonfiction', 'Philosophy', 'Fran...",5024,341,4.22,"{'5': '2,227', '4': '1,911', '3': '707', '2': ..."
1787,1787,23721,https://images-na.ssl-images-amazon.com/images...,"Nausicaä of the Valley of the Wind, Vol. 6","In a long-ago war, humankind set off a devasta...","['159 pages, Paperback']","['First published January 1, 1993']",https://www.goodreads.com/author/show/4263.Hay...,Hayao Miyazaki,['159'],"['Manga', 'Comics', 'Graphic Novels', 'Fantasy...",2576,75,4.60,"{'5': '1,746', '4': '664', '3': '145', '2': '1..."
1788,1788,23722,https://images-na.ssl-images-amazon.com/images...,"Nausicaä of the Valley of the Wind, Vol. 5","The Torumekian army is moving house, destroy a...","['151 pages, Paperback']","['First published January 1, 1991']",https://www.goodreads.com/author/show/4263.Hay...,Hayao Miyazaki,['151'],"['Manga', 'Graphic Novels', 'Comics', 'Fantasy...",2666,68,4.58,"{'5': '1,767', '4': '711', '3': '168', '2': '1..."
1789,1789,23724,https://images-na.ssl-images-amazon.com/images...,"Nausicaä of the Valley of the Wind, Vol. 7","Nach den ""Sieben Tagen des Feuers"" ist die Erd...","['223 pages, Paperback']","['First published January 1, 1995']",https://www.goodreads.com/author/show/4263.Hay...,Hayao Miyazaki,['223'],"['Manga', 'Graphic Novels', 'Fantasy', 'Comics...",2443,148,4.60,"{'5': '1,677', '4': '584', '3': '152', '2': '2..."
1818,1818,24113,https://images-na.ssl-images-amazon.com/images...,"Gödel, Escher, Bach: An Eternal Golden Braid",Douglas Hofstadter's book is concerned directl...,"['756 pages, Paperback']","['First published April 1, 1979']",https://www.goodreads.com/author/show/3034502....,Douglas R. Hofstadter,['756'],"['Science', 'Nonfiction', 'Philosophy', 'Mathe...",49512,2267,4.29,"{'5': '27,385', '4': '13,412', '3': '5,700', '..."
1826,1826,24280,https://images-na.ssl-images-amazon.com/images...,Les Misérables,"Victor Hugo's tale of injustice, heroism and l...","['1463 pages, Mass Market Paperback']","['First published January 1, 1862']",https://www.goodreads.com/author/show/13661.Vi...,Victor Hugo,['1463'],"['Classics', 'Fiction', 'Historical Fiction', ...",800123,22914,4.20,"{'5': '398,449', '4': '235,743', '3': '114,242..."
1974,1974,27736,https://images-na.ssl-images-amazon.com/images...,Rhinocéros,"""Tous les chats sont mortels. Socrate est mort...","['246 pages, Paperback']","['First published January 1, 1959']",https://www.goodreads.com/author/show/7689.Eug...,Eugène Ionesco,['246'],"['Plays', 'Classics', 'Theatre', 'France', 'Fi...",16804,847,3.83,"{'5': '4,823', '4': '6,356', '3': '4,051', '2'..."

In [25]:
mask = df["book_title"].apply(has_non_english_letter)

df = df[~mask].copy()

In [26]:
df

,Unnamed: 0,book_id,cover_image_uri,book_title,book_details,format,publication_info,authorlink,author,num_pages,genres,num_ratings,num_reviews,average_rating,rating_distribution
0,0,1,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Half-Blood Prince,"It is the middle of the summer, but there is a...","['652 pages, Paperback']","['First published July 16, 2005']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['652'],"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",3292516,58398,4.58,"{'5': '2,244,154', '4': '775,028', '3': '219,8..."
1,1,2,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Order of the Phoenix,Harry Potter is about to start his fifth year ...,"['912 pages, Paperback']","['First published June 21, 2003']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['912'],"['Young Adult', 'Fiction', 'Magic', 'Childrens...",3401709,64300,4.50,"{'5': '2,178,760', '4': '856,178', '3': '293,2..."
2,2,3,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Sorcerer's Stone,Harry Potter has no idea how famous he is. Tha...,"['309 pages, Hardcover']","['First published June 26, 1997']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['309'],"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",10116247,163493,4.47,"{'5': '6,544,542', '4': '2,348,390', '3': '856..."
3,3,5,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Prisoner of Azkaban,"Harry Potter, along with his best friends, Ron...","['435 pages, Mass Market Paperback']","['First published July 8, 1999']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['435'],"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",4215031,84959,4.58,"{'5': '2,892,322', '4': '970,190', '3': '287,7..."
4,4,6,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Goblet of Fire,It is the summer holidays and soon Harry Potte...,"['734 pages, Paperback']","['First published July 8, 2000']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['734'],"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",3718209,69961,4.57,"{'5': '2,500,070', '4': '899,496', '3': '259,7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16219,16219,208567667,https://images-na.ssl-images-amazon.com/images...,The Art of Avoiding Your Alpha,"My soulmate bought me a sugar cookie… and now,...","['221 pages, Kindle Edition']","['Published March 13, 2024']",https://www.goodreads.com/author/show/20827982...,Lola Glass,['221'],"['Science Fiction Fantasy', 'Fantasy', 'Novels...",1515,88,4.01,"{'5': '549', '4': '527', '3': '357', '2': '68'..."
16221,16221,208877648,https://images-na.ssl-images-amazon.com/images...,The Descent,"Set in the 1950s, The Descent asks the questio...","['268 pages, Paperback']","['First published January 1, 1952']",https://www.goodreads.com/author/show/151154.F...,Fritz Peters,['268'],['Fiction'],4,0,4.75,"{'5': '3', '4': '1', '3': '0', '2': '0', '1': ..."
16222,16222,209251042,https://images-na.ssl-images-amazon.com/images...,FDR Unmasked: 73 Years of Medical Cover-ups Th...,THE HIDDEN ILLNESSES THAT SHAPED FDR’S LIFE AN...,"['316 pages, Paperback']","['Published February 27, 2024']",https://www.goodreads.com/author/show/2991326....,Steven Lomazow,['316'],"['Drama', 'Novels', 'Contemporary']",986,11,4.32,"{'5': '469', '4': '431', '3': '38', '2': '33',..."
16223,16223,209441121,https://images-na.ssl-images-amazon.com/images...,Code Yellow in Gretna Green,"In Gateway terminology, a ""Code Yellow"" signif...","['776 pages, Kindle Edition']","['Published March 28, 2024']",https://www.goodreads.com/author/show/22515164...,Linzi Day,['776'],"['Science Fiction Fantasy', 'Fantasy', 'Fictio...",1109,106,4.61,"{'5': '764', '4': '266', '3': '74', '2': '4', ..."
16224,16224,209607645,https://images-na.ssl-images-amazon.com/images...,Shadow's Siege,Shadow Island is under siege.Just a few short ...,"['254 pages, Kindle Edition']","['Published April 25, 2024']",https://www.goodreads.com/author/show/19007338...,Mary Stone,['254'],"['Drama', 'Novels', 'Crime', 'Thriller', 'Susp...",1271,37,4.64,"{'5': '914', '4': '277', '3': '70', '2': '5', ..."

In [27]:
def clean_genres(x):
    if pd.isna(x):
        return []
    
    x = str(x).strip("[]")
    
    return [
        genre.strip().strip("'\"")
        for genre in x.split(",")
        if genre.strip()
    ]

df['genres'] = df['genres'].apply(clean_genres)
df = df.explode('genres')

In [28]:
df

,Unnamed: 0,book_id,cover_image_uri,book_title,book_details,format,publication_info,authorlink,author,num_pages,genres,num_ratings,num_reviews,average_rating,rating_distribution
0,0,1,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Half-Blood Prince,"It is the middle of the summer, but there is a...","['652 pages, Paperback']","['First published July 16, 2005']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['652'],Fantasy,3292516,58398,4.58,"{'5': '2,244,154', '4': '775,028', '3': '219,8..."
0,0,1,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Half-Blood Prince,"It is the middle of the summer, but there is a...","['652 pages, Paperback']","['First published July 16, 2005']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['652'],Young Adult,3292516,58398,4.58,"{'5': '2,244,154', '4': '775,028', '3': '219,8..."
0,0,1,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Half-Blood Prince,"It is the middle of the summer, but there is a...","['652 pages, Paperback']","['First published July 16, 2005']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['652'],Fiction,3292516,58398,4.58,"{'5': '2,244,154', '4': '775,028', '3': '219,8..."
0,0,1,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Half-Blood Prince,"It is the middle of the summer, but there is a...","['652 pages, Paperback']","['First published July 16, 2005']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['652'],Magic,3292516,58398,4.58,"{'5': '2,244,154', '4': '775,028', '3': '219,8..."
0,0,1,https://images-na.ssl-images-amazon.com/images...,Harry Potter and the Half-Blood Prince,"It is the middle of the summer, but there is a...","['652 pages, Paperback']","['First published July 16, 2005']",https://www.goodreads.com/author/show/1077326....,J.K. Rowling,['652'],Childrens,3292516,58398,4.58,"{'5': '2,244,154', '4': '775,028', '3': '219,8..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16224,16224,209607645,https://images-na.ssl-images-amazon.com/images...,Shadow's Siege,Shadow Island is under siege.Just a few short ...,"['254 pages, Kindle Edition']","['Published April 25, 2024']",https://www.goodreads.com/author/show/19007338...,Mary Stone,['254'],Drama,1271,37,4.64,"{'5': '914', '4': '277', '3': '70', '2': '5', ..."
16224,16224,209607645,https://images-na.ssl-images-amazon.com/images...,Shadow's Siege,Shadow Island is under siege.Just a few short ...,"['254 pages, Kindle Edition']","['Published April 25, 2024']",https://www.goodreads.com/author/show/19007338...,Mary Stone,['254'],Novels,1271,37,4.64,"{'5': '914', '4': '277', '3': '70', '2': '5', ..."
16224,16224,209607645,https://images-na.ssl-images-amazon.com/images...,Shadow's Siege,Shadow Island is under siege.Just a few short ...,"['254 pages, Kindle Edition']","['Published April 25, 2024']",https://www.goodreads.com/author/show/19007338...,Mary Stone,['254'],Crime,1271,37,4.64,"{'5': '914', '4': '277', '3': '70', '2': '5', ..."
16224,16224,209607645,https://images-na.ssl-images-amazon.com/images...,Shadow's Siege,Shadow Island is under siege.Just a few short ...,"['254 pages, Kindle Edition']","['Published April 25, 2024']",https://www.goodreads.com/author/show/19007338...,Mary Stone,['254'],Thriller,1271,37,4.64,"{'5': '914', '4': '277', '3': '70', '2': '5', ..."
16224,16224,209607645,https://images-na.ssl-images-amazon.com/images...,Shadow's Siege,Shadow Island is under siege.Just a few short ...,"['254 pages, Kindle Edition']","['Published April 25, 2024']",https://www.goodreads.com/author/show/19007338...,Mary Stone,['254'],Suspense,1271,37,4.64,"{'5': '914', '4': '277', '3': '70', '2': '5', ..."

In [29]:
# Find the 20 most frequent genres
top_20_genres = df['genres'].value_counts().head(20).index

# Replace all other genres with "Other"
df['genres'] = df['genres'].where(
    df['genres'].isin(top_20_genres),
    'Other'
)

In [30]:
df = df.sort_values(
    ['genres', 'average_rating'],
    ascending=[True, False]
)

In [31]:
df

,Unnamed: 0,book_id,cover_image_uri,book_title,book_details,format,publication_info,authorlink,author,num_pages,genres,num_ratings,num_reviews,average_rating,rating_distribution
13092,13092,17332218,https://images-na.ssl-images-amazon.com/images...,Words of Radiance,"Words of Radiance, Book Two of the Stormlight ...","['1087 pages, Hardcover']","['First published March 4, 2014']",https://www.goodreads.com/author/show/38550.Br...,Brandon Sanderson,['1087'],Adult,355368,21983,4.76,"{'5': '283,791', '4': '60,226', '3': '9,190', ..."
14246,14246,29227774,https://images-na.ssl-images-amazon.com/images...,Light Bringer,Darrow returns as Pierce Brown’s New York Time...,"['682 pages, Hardcover']","['First published July 25, 2023']",https://www.goodreads.com/author/show/6474348....,Pierce Brown,['682'],Adult,37636,4047,4.75,"{'5': '29,833', '4': '6,503', '3': '1,065', '2..."
11057,11057,6606305,https://images-na.ssl-images-amazon.com/images...,Black Dagger Brotherhood: Boxed Set #1-6,Perfect for fans of Ward's bestselling Black D...,['Mass Market Paperback'],"['First published September 29, 2009']",https://www.goodreads.com/author/show/20248.J_...,J.R. Ward,[None],Adult,8799,233,4.70,"{'5': '6,962', '4': '1,259', '3': '400', '2': ..."
11352,11352,7235533,https://images-na.ssl-images-amazon.com/images...,The Way of Kings,From #1 New York Times bestselling author Bran...,"['1007 pages, Hardcover']","['First published August 31, 2010']",https://www.goodreads.com/author/show/38550.Br...,Brandon Sanderson,['1007'],Adult,500546,36210,4.66,"{'5': '372,916', '4': '97,453', '3': '21,341',..."
14031,14031,25686515,https://images-na.ssl-images-amazon.com/images...,El camino de los reyes,Una obra maestra tan ambiciosa como fascinante...,"['1196 pages, Hardcover']","['First published August 31, 2010']",https://www.goodreads.com/author/show/38550.Br...,Brandon Sanderson,['1196'],Adult,500807,36235,4.66,"{'5': '373,109', '4': '97,510', '3': '21,349',..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12338,12338,12393909,https://images-na.ssl-images-amazon.com/images...,Revealing Eden,Eden Newman must mate before her 18th birthday...,"['307 pages, Hardcover']","['First published October 1, 2011']",https://www.goodreads.com/author/show/9414.Vic...,Victoria Foyt,['307'],Young Adult,983,372,2.00,"{'5': '127', '4': '81', '3': '75', '2': '81', ..."
10837,10837,6350887,https://images-na.ssl-images-amazon.com/images...,Maradonia and the Seven Bridges,The Maradonia Sagastarts as an everyday story....,"['810 pages, Paperback']","['First published January 1, 2008']",https://www.goodreads.com/author/show/2880005....,Gloria Tesch,['810'],Young Adult,115,50,1.90,"{'5': '23', '4': '1', '3': '1', '2': '7', '1':..."
12841,12841,15842524,https://images-na.ssl-images-amazon.com/images...,Adapting Eden,"In the sequel to the dystopian novel, Revealin...","['299 pages, Hardcover']","['First published January 25, 2013']",https://www.goodreads.com/author/show/9414.Vic...,Victoria Foyt,['299'],Young Adult,82,25,1.61,"{'5': '9', '4': '1', '3': '3', '2': '5', '1': ..."
14679,14679,35800325,https://images-na.ssl-images-amazon.com/images...,Handbook for Mortals,Zade Holder has always been a free-spirited yo...,"['448 pages, Hardcover']","['First published August 15, 2017']",https://www.goodreads.com/author/show/17052081...,Lani Sarem,['448'],Young Adult,959,400,1.29,"{'5': '42', '4': '13', '3': '18', '2': '36', '..."
15115,15115,43275562,https://images-na.ssl-images-amazon.com/images...,Reaper's Creek,A young boy named Daniel encounters creatures ...,"['122 pages, Paperback']","['First published December 14, 2018']",https://www.goodreads.com/author/show/13740405...,Onision,['122'],Young Adult,334,100,1.14,"{'5': '7', '4': '3', '3': '1', '2': '8', '1': ..."

In [32]:
df['genre_rank'] = df.groupby('genres').cumcount() + 1

In [33]:
df = df.sort_values(
    ['genre_rank', 'genres']
)

In [34]:
df['genres'].unique()

<ArrowStringArray>
[             'Adult',          'Adventure',          'Audiobook',
          'Childrens',           'Classics',       'Contemporary',
            'Fantasy',            'Fiction',         'Historical',
 'Historical Fiction',             'Horror',         'Literature',
            'Mystery',         'Nonfiction',             'Novels',
              'Other',         'Paranormal',            'Romance',
    'Science Fiction',           'Thriller',        'Young Adult']
Length: 21, dtype: str

In [35]:
homepage = df.sort_values(
    ["genre_rank", "genres"]
)

In [36]:
print(
    homepage[
        ["genres", "genre_rank", "book_title", "average_rating"]
    ].head(40)
)

                   genres  genre_rank  \
13092               Adult           1
1833            Adventure           1
13092           Audiobook           1
7963            Childrens           1
1867             Classics           1
14100        Contemporary           1
13135             Fantasy           1
4836              Fiction           1
15834          Historical           1
4083   Historical Fiction           1
9131               Horror           1
1833           Literature           1
15260             Mystery           1
15207          Nonfiction           1
8762               Novels           1
7439                Other           1
11057          Paranormal           1
15834             Romance           1
14246     Science Fiction           1
15260            Thriller           1
12568         Young Adult           1
14246               Adult           2
7963            Adventure           2
13660           Audiobook           2
5               Childrens           2
7763             Classics           2
15693        Contemporary           2
15834             Fantasy           2
15834             Fiction           2
4083           Historical           2
1833   Historical Fiction           2
10000              Horror           2
5729           Literature           2
15202             Mystery           2
15335          Nonfiction           2
16224              Novels           2
7583                Other           2
12810          Paranormal           2
15630             Romance           2
15092     Science Fiction           2

                                              book_title  average_rating
13092                                  Words of Radiance            4.76
1833                  The Complete Aubrey/Maturin Novels            4.76
13092                                  Words of Radiance            4.76
7963                         Harry Potter Series Box Set            4.74
1867                      The Complete Calvin and Hobbes            4.81
14100                               Some Kind of Perfect            4.65
13135                                  Hunt for the Star            4.83
4836                           The Knights of King Midas            4.83
15834  Heaven Official's Blessing: Tian Guan Ci Fu (N...            4.82
4083                            Mark of the Lion Trilogy            4.78
9131                      The Absolute Sandman, Volume 3            4.69
1833                  The Complete Aubrey/Maturin Novels            4.76
15260                    Addressed To Her: A Short Story            4.80
15207     100 Fun Bible Facts: The Exciting way to Learn            4.93
8762                                        The Fortress            4.67
7439                           Bill Cosby: Coming at You            5.00
11057           Black Dagger Brotherhood: Boxed Set #1-6            4.70
15834  Heaven Official's Blessing: Tian Guan Ci Fu (N...            4.82
14246                                      Light Bringer            4.75
15260                    Addressed To Her: A Short Story            4.80
12568                                           Blackout            4.82
14246                                      Light Bringer            4.75
7963                         Harry Potter Series Box Set            4.74
13660                       The Warden and the Wolf King            4.75
5                      Harry Potter Boxed Set, Books 1-5            4.72
7763                                               Nutuk            4.81
15693                           Heartstopper: Volume 1-4            4.65
15834  Heaven Official's Blessing: Tian Guan Ci Fu (N...            4.82
15834  Heaven Official's Blessing: Tian Guan Ci Fu (N...            4.82
4083                            Mark of the Lion Trilogy            4.78
1833                  The Complete Aubrey/Maturin Novels            4.76
10000                     The Absolute Sandman, Volume 4            4.69
5729                                The moonlight sonata            4.70
15202                                The Mindf*ck Series            4.63
15335  100 Bible Facts About Jesus: The Exciting way ...            4.90
16224                                     Shadow's Siege            4.64
7583      Before you're a stranger: New & selected poems            5.00
12810  Clockwork Angel; Clockwork Prince; Clockwork P...            4.66
15630      All the Young Dudes - Volume Two: Years 5 - 7            4.81
15092                                    Down and Rising            4.72

In [37]:
df["genres"] = df.groupby(
    ["book_title", "author"]
)["genres"].transform(
    lambda x: ", ".join(x.dropna().astype(str).unique())
)

df = df.drop_duplicates(
    subset=["book_title", "author"]
).reset_index(drop=True)

In [38]:
df.to_csv("dataset/books_cleaned.csv", index=False)